server:
  servlet:
    context-path: /springboot4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: accp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true